return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "go",
        "hcl",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "terraform",
        "tsx",
        "typescript",
        "vim",
        "yaml",
      },
    },
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "ansible-language-server",
        "bash-language-server",
        "css-lsp",
        "dockerfile-language-server",
        "groovy-language-server",
        "helm-ls",
        "lua-language-server",
        "ruff",
        "ruff-lsp",
        "rust-analyzer",
        "shellcheck",
        "shellharden",
        "shfmt",
        "stylua",
        "terraform-ls",
        "tflint",
        "tfsec",
        "typescript-language-server",
      },
    },
  },
}
